export const FREE_EXAM_LIST_REQUEST = "FREE_EXAM_LIST_REQUEST ";
export const FREE_EXAM_LIST_SUCCESS = "FREE_EXAM_LIST_SUCCESS ";
export const FREE_EXAM_LIST_FAIL = " FREE_EXAM_LIST_FAIL";

export const START_EXAM_REQUEST = "START_EXAM_REQUEST ";
export const START_EXAM_SUCCESS = "START_EXAM_SUCCESS ";
export const START_EXAM_FAIL = " START_EXAM_FAIL";
