export const FREE_EXAM_LIST_REQUEST = "FREE_EXAM_LIST_REQUEST ";
export const FREE_EXAM_LIST_SUCCESS = "FREE_EXAM_LIST_SUCCESS ";
export const FREE_EXAM_LIST_FAIL = " FREE_EXAM_LIST_FAIL";

export const START_EXAM_REQUEST = "START_EXAM_REQUEST ";
export const START_EXAM_SUCCESS = "START_EXAM_SUCCESS ";
export const START_EXAM_FAIL = " START_EXAM_FAIL";

export const SAVE_QUESTION_REQUEST = "SAVE_QUESTION_REQUEST ";
export const SAVE_QUESTION_SUCCESS = "SAVE_QUESTION_SUCCESS ";
export const SAVE_QUESTION_FAIL = " SAVE_QUESTION_FAIL";

export const BOOKMARK_QUESTION_REQUEST = "BOOKMARK_QUESTION_REQUEST ";
export const BOOKMARK_QUESTION_SUCCESS = "BOOKMARK_QUESTION_SUCCESS ";
export const BOOKMARK_QUESTION_FAIL = " BOOKMARK_QUESTION_FAIL";

export const UNBOOKMARK_QUESTION_REQUEST = "UNBOOKMARK_QUESTION_REQUEST ";
export const UNBOOKMARK_QUESTION_SUCCESS = "UNBOOKMARK_QUESTION_SUCCESS ";
export const UNBOOKMARK_QUESTION_FAIL = " UNBOOKMARK_QUESTION_FAIL";

export const MARK_REVIEW_QUESTION_REQUEST = "MARK_REVIEW_QUESTION_REQUEST ";
export const MARK_REVIEW_QUESTION_SUCCESS = "MARK_REVIEW_QUESTION_SUCCESS ";
export const MARK_REVIEW_QUESTION_FAIL = " MARK_REVIEW_QUESTION_FAIL";

export const RESET_ANSWER_REQUEST = "RESET_ANSWER_REQUEST ";
export const RESET_ANSWER_SUCCESS = "RESET_ANSWER_SUCCESS ";
export const RESET_ANSWER_FAIL = " RESET_ANSWER_FAIL";

export const SUBMIT_EXAM_REQUEST = "SUBMIT_EXAM_REQUEST ";
export const SUBMIT_EXAM_SUCCESS = "SUBMIT_EXAM_SUCCESS ";
export const SUBMIT_EXAM_FAIL = " SUBMIT_EXAM_FAIL";

// export const OPTION_SELECT_REQUEST = "OPTION_SELECT_REQUEST ";
// export const OPTION_SELECT = "OPTION_SELECT";
// export const OPTION_SELECT_FAIL = " OPTION_SELECT_FAIL";
