import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faBookmark,
  faChartBar,
  faCompass,
  faCreditCard,
  faHome,
  faQuestionCircle,
  faSearch,
  faShoppingCart,
  faStar,
  faTimesCircle,
  faTrophy,
  faUser,
  faCaretDown,
  faTimes,
  faArrowLeft,
  faLock,
  faBell,
  faPlus,
  faArrowRight,
} from "@fortawesome/free-solid-svg-icons";
import { faStar as faRegularStar } from "@fortawesome/free-regular-svg-icons";

library.add(
  faHome,
  faShoppingCart,
  faTrophy,
  faChartBar,
  faBookmark,
  faTimesCircle,
  faSearch,
  faCompass,
  faCreditCard,
  faQuestionCircle,
  faUser,
  faStar,
  faCaretDown,
  faTimes,
  faArrowLeft,
  faArrowRight,
  faLock,
  faTimes,
  faBell,
  faPlus,
  faStar,
  faRegularStar
);
